# mytuple = ("apple", "banana", "cherry")
# print (mytuple)
# thistuple = ("apple", "banan", "cherry", "apple", "cherry")
# print(thistuple)
# print (len (thistuple))
# thistuple = ("apple",)
# print(type(thistuple))

# #NOT a tuple
# thistuple = ("apple")
# print(type(thistuple))
# tuple1 = ("apple", "banana", "cherry")
# tuple2 = (1, 5, 7, 9, 3)
# tuple3 = (True, False, False)
# tuple4 = ("abc", 34, True, 40, "male")
# print (type (mytuple))
mytuple = ("apple", "banana", "cherry")
print(type(mytuple))
thistuple = tuple(("apple", "banana", "cherry"))
print(thistuple)
